name = "jm-contact-form"
main = "contact-worker.js"
compatibility_date = "2026-01-01"

[[ratelimits]]
name = "CONTACT_FORM_RATE_LIMITER"
namespace_id = "1001"

  [ratelimits.simple]
  limit = 5
  period = 60
